#!/usr/bin/env python3
"""HuiChat DB package: modularized helpers behind the legacy database.py facade."""

from db.core import (
    init_db_pool,
    _acquire_conn,
    _release_conn,
    get_db,
    close_db,
    init_database,
    get_db_identity,
    get_schema_version,
    init_app,
)
from db.migrations import (
    _ensure_schema_meta_table,
    _checksum_path,
    _load_python_migration,
    list_available_migrations,
    _get_applied_migration_rows,
    apply_migrations,
)
from db.shared import (
    JSON_ROOMS_PATH,
    MIGRATIONS_DIR,
    SCHEMA_META_TABLE,
    MigrationSpec,
)

from db.rooms import (
    _read_rooms_json,
    _official_room_names_from_data,
    _official_room_names_from_json,
    get_blocked_users,
    get_pending_friend_requests,
    load_rooms_from_json,
    consume_room_invites,
    record_custom_room_membership,
    get_custom_room_user_role,
    can_user_moderate_custom_room,
    revoke_custom_room_access,
    set_room_message_expiry,
    get_room_message_expiry,
    cleanup_expired_room_messages,
    is_user_verified,
    get_custom_room_meta,
    can_user_access_custom_room,
    can_user_join_custom_room,
    touch_custom_room_activity,
    cleanup_expired_custom_rooms,
    delete_custom_room_persisted_state,
    get_friends_for_user,
    get_all_rooms,
    create_room_if_missing,
    create_autoscaled_room_if_missing,
    increment_room_count,
    cleanup_expired_autoscaled_rooms,
    dump_tables,
    seed_rooms_from_file,
)

from db.auth import (
    _pbkdf2_key,
    _encrypt_private_key_v2,
    _decrypt_private_key_blob,
    _generate_and_encrypt_rsa_keypair,
    generate_user_keypair_for_password,
    create_user_with_keys,
    ensure_user_has_default_avatar,
    get_public_key_for_username,
    user_exists,
    email_in_use,
    ensure_user_has_keys,
    get_encrypted_private_key_for_username,
    store_auth_token,
    revoke_auth_token,
    revoke_all_tokens_for_user,
    is_auth_token_revoked,
    create_auth_session,
    touch_auth_session,
    touch_auth_session_activity,
    is_auth_session_active,
    get_auth_session_state,
    get_session_id_for_token,
    attach_session_to_token,
    revoke_auth_session,
    revoke_other_sessions_for_user,
    revoke_all_sessions_for_user,
    revoke_all_sessions_and_tokens_for_user,
    list_auth_sessions,
    revoke_all_tokens_global,
    is_refresh_token_active,
    get_refresh_token_meta,
    is_refresh_token_usable,
    rotate_refresh_token,
    touch_auth_token,
)


from db.schema import (
    _log_table_owner_mismatch,
    ensure_online_column,
    ensure_presence_columns,
    ensure_chat_rooms_table,
    sync_chat_room_kinds,
    ensure_users_key_columns,
    ensure_users_security_columns,
    ensure_account_recovery_schema,
    ensure_auth_session_schema,
    ensure_user_verified_column,
    ensure_custom_rooms_schema,
    ensure_room_message_expiry_schema,
    _create_full_schema,
    _seed_roles_permissions,
    _legacy_bootstrap_schema,
)
